### ISSUE TITLE
Mamba missing in snakemake environment

### ISSUE THREAD

**Issue by sneuensc** [snakemake/snakemake-workflow-catalog#12]
Thank you for the workflow catalog, it is a great initiative.

There is an inconsistency in the 'Usage' instructions for the 'standardized usage packages'.

In step 1 (install Snakemake and Snakedeploy) the conda environment is generated
`mamba create -c bioconda -c conda-forge --name snakemake snakemake snakedeploy`

In step 4 (run workflow) the recommendation to run the workflow is 
`snakemake --cores all --use-conda `

By default the local conda environments are generated and loaded using **mamba**, however mama was never installed. I recommend installing mamba within step 1.

**Comment by johanneskoester** [comment]
Hi! We mention that in the first sentence of step 1. Maybe it should be highlighted more? I intentionally did not put the explicit steps to install mamba there, because there are many different ways, which also might change further in the future. Hence I thought it might be better to link to the mamba docs.
